Header header
#Vector3Ext drag_force

float64 resistance_force
float64 down_force

float64 delta
float64 dc

float64 front_left_steering_angle
float64 front_right_steering_angle
float64 delta_measured

float64 vx
float64 vy
float64 r

bool torque_ok 

float64 alpha_f
float64 alpha_f_l
float64 alpha_f_r
float64 alpha_r_l
float64 alpha_r
float64 alpha_r_r

float64 Fy_f
float64 Fy_f_l
float64 Fy_f_r
float64 Fy_r
float64 Fy_r_l
float64 Fy_r_r

float64 Fx
